quotes=["Believe in yourself and all that you are.", 
        "Don’t watch the clock; do what it does. Keep going.",
        "Success is what comes after you stop making excuses.", 
        "The harder you work for something, the greater you'll feel when you achieve it.", 
        "Dream bigger. Do bigger.", 
        "Don't stop when you're tired. Stop when you're done.", 
        "Push yourself, because no one else is going to do it for you.", 
        "Do something today that your future self will thank you for.", 
        "It always seems impossible until it is done.", 
        "Great things never come from comfort zones.", 
        "Believe you can and you're halfway there.", 
        "Opportunities don't happen. You create them.", 
        "Work hard in silence, let your success be your noise.", 
        "The future depends on what you do today.", 
        "You are capable of amazing things.", 
        "Start where you are. Use what you have. Do what you can.",
        "Doubt kills more dreams than failure ever will.", 
        "Stay positive, work hard, make it happen.", 
        "Little things make big days.", 
        "Your only limit is your mind."
]